[package]
name = "s3bat"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.55"
aws-sdk-s3 = "0.28"
bat = "0.23"
clap = { version = "4.4", features = ["derive"] }
regex = "1.9"
tokio = { version = "1.29", features = ["full"] }
